core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("pages.urls")),
    path("shop/", include("shop.urls")),
]

pages/urls.py
from django.urls import path

from . import views

# app_name = "pages"

urlpatterns = [
    path("", views.home, name="home"),
    path("about-us/", views.about, name="about"),
    path("contact-us/", views.contact, name="contact"),
    path("privacy-policy/", views.privacy_policy, name="privacy"),
    path("work-for-us/", views.jobs, name="jobs"),
]

shop/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.get_product_list, name="product_list"),
    path("add-to-cart/", views.add_to_cart, name="add_to_cart"),
    path("cart/", views.get_cart_items, name="shopping_cart"),
    path("stripe-config/", views.get_stripe_config, name="stripe_config"),
    path("checkout/", views.create_checkout_session),
    path("success/", views.payment_success),
    path("cancel/", views.payment_cancel),
]

pages/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.db import models


class Product(models.Model):    # shop_product
    EUR = "EUR"
    USD = "USD"
    ALL = "ALL"
    CURRENCY_CHOICES = [
        (EUR, "€"),
        (USD, "$"),
        (ALL, "Lek")
    ]

    name = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    currency = models.CharField(max_length=3, choices=CURRENCY_CHOICES)
    description = models.TextField(null=True, blank=True)

    class Meta:
        db_table = "products"

pages/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render


def home(request: HttpRequest) -> HttpResponse:
    return render(request, "pages/home.html", context={})


def about(request: HttpRequest) -> HttpResponse:
    return render(request, "pages/about.html")


def contact(request: HttpRequest) -> HttpResponse:
    return render(request, "pages/contact.html")


def privacy_policy(request: HttpRequest) -> HttpResponse:
    return render(request, "pages/privacy_policy.html")


def jobs(request: HttpRequest) -> HttpResponse:
    return render(request, "pages/jobs.html")

shop/views.py
import stripe

from django.http import HttpRequest, HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST, require_GET
from django.conf import settings

from .models import Product


def get_product_list(request):
    products = Product.objects.all()
    return render(request, "shop/product_list.html", context={
        "products": products
    })


@require_POST
def add_to_cart(request: HttpRequest) -> HttpResponse:
    product_id = request.POST["product_id"]
    cart = request.session.get("shopping_cart", {})
    cart[product_id] = cart.get(product_id, 0) + 1
    request.session["shopping_cart"] = cart
    request.session.modified = True
    return redirect("product_list")


def get_cart_items(request):
    cart = request.session.get("shopping_cart", {})
    product_ids = [int(key) for key in cart.keys()]
    products = Product.objects.filter(pk__in=product_ids).all()
    items = []
    for product in products:
        quantity = int(cart.get(str(product.pk)))
        item = {
            "name": product.name,
            "quantity": quantity,
            "price": product.price,
            "total": product.price * quantity,
        }
        items.append(item)
    return render(request, "shop/cart.html", context={
        "items": items
    })


@require_GET
def get_stripe_config(request):
    config = {"publicKey": settings.STRIPE_PUBLISHABLE_KEY}
    return JsonResponse(config)


@require_GET
def create_checkout_session(request):
    domain_url = 'http://localhost:8000/'
    stripe.api_key = settings.STRIPE_SECRET_KEY
    try:
        # Create new Checkout Session for the order
        # Other optional params include:
        # [billing_address_collection] - to display billing address details on the page
        # [customer] - if you have an existing Stripe Customer ID
        # [payment_intent_data] - capture the payment later
        # [customer_email] - prefill the email input in the form
        # For full details see https://stripe.com/docs/api/checkout/sessions/create


        cart = request.session.get("shopping_cart", {})
        product_ids = [int(key) for key in cart.keys()]
        products = Product.objects.filter(pk__in=product_ids).all()
        items = []
        for product in products:
            quantity = int(cart.get(str(product.pk)))
            item = {
                "quantity": quantity,
                "price_data": {
                    "currency": "usd",
                    "product_data": {
                        "name": product.name,
                        "description": product.description,
                    },
                    "unit_amount": str(int(product.price * 100)),
                }
            }
            items.append(item)

        # ?session_id={CHECKOUT_SESSION_ID} means the redirect will have the session ID set as a query param
        checkout_session = stripe.checkout.Session.create(
            success_url=domain_url + 'shop/success?session_id={CHECKOUT_SESSION_ID}',
            cancel_url=domain_url + 'shop/cancel/',
            payment_method_types=['card'],
            mode='payment',
            line_items=items
        )
        return JsonResponse({'sessionId': checkout_session['id']})
    except Exception as e:
        return JsonResponse({'error': str(e)})


def payment_success(request):
    request.session["shopping_cart"] = {}
    request.session.modified = True
    return render(request, "shop/success.html")


def payment_cancel(request):
    return render(request, "shop/cancel.html")

pages/templates/pages/about.html
<!DOCTYPE html>
{% load i18n %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% translate "About Us" %} - {% translate "Our Page" %}</title>
</head>
<body>
    <ul>
        <li><a href="{% url 'home' %}">Home</a></li>
        <li><a href="{% url 'about' %}">About Us</a></li>
        <li><a href="{% url 'contact' %}">Contact Us</a></li>
        <li><a href="{% url 'privacy' %}">Privacy Policy</a></li>
        <li><a href="{% url 'jobs' %}">Work for Us</a></li>
    </ul>
    <h1>{% translate "About Us" %}</h1>
</body>
</html>

pages/templates/pages/contact.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
<h1>{% translate "Contact Us" %}</h1>
{% endblock content %}

pages/templates/pages/home.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
<h1>{% translate "Homepage" %}</h1>
{% endblock content %}

pages/templates/pages/jobs.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
<h1>{% translate "Work for Us" %}</h1>
<p>No positions available</p>
{% endblock content %}

pages/templates/pages/privacy_policy.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
<h1>{% translate "Privacy Policy" %}</h1>
<p>We don't share any private info</p>
{% endblock content %}

shop/templates/shop/cancel.html
{% extends 'base.html' %}

{% block content %}
<p>payment cancelled</p>
{% endblock content %}

shop/templates/shop/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>Cart Contents</h1>
<table>
    <thead>
        <tr>
            <th>Product</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Total</th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <th colspan="4" style="text-align: right;">
                <button id="btnCheckout" type="submit">Checkout</button>
            </th>
        </tr>
    </tfoot>
    <tbody>
    {% for item in items %}
        <tr>
            <td>{{ item.name }}</td>
            <td>{{ item.quantity }}</td>
            <td>{{ item.price }}</td>
            <td>{{ item.total }}</td>
        </tr>
    {% empty %}
        <tr>
            <td colspan="4">No items added to cart yet!</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock content %}

{% block scripts %}
<script src="https://js.stripe.com/v3/"></script>
<script src="{% static 'main.js' %}"></script>
{% endblock scripts %}

shop/templates/shop/product_list.html
{% extends 'base.html' %}
{% block title %}Products - {{ block.super }}{% endblock title %}
{% block content %}
    <h1>Products on Sale</h1>
    <table>
        <thead>
            <tr>
                <th>Product</th>
                <th>Price</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {% for product in products %}
            <tr>
                <td>{{ product.name }}</td>
                <td>{{ product.price }}{{ product.get_currency_display }}</td>
                <td>
                    <form method="post" action="{% url 'add_to_cart' %}">
                        {% csrf_token %}
                        <input type="hidden" name="product_id" value="{{ product.pk }}">
                        <button type="submit">+</button>
                    </form>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="3">No products have been added yet!</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock content %}

shop/templates/shop/success.html
{% extends 'base.html' %}

{% block content %}
<p>Bought successfully</p>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
{% load i18n %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    {% block styles %}{% endblock styles %}
</head>
<body>
    <header>
        <nav>
            <ul>
                <li><a href="{% url 'home' %}">Home</a></li>
                <li><a href="{% url 'product_list' %}">Shop</a></li>
                <li><a href="{% url 'about' %}">About Us</a></li>
                <li><a href="{% url 'contact' %}">Contact Us</a></li>
                <li><a href="{% url 'privacy' %}">Privacy Policy</a></li>
                <li><a href="{% url 'jobs' %}">Work for Us</a></li>
                <li>
                    <a href="{% url 'shopping_cart' %}">Shopping Cart</a>
                </li>
            </ul>
        </nav>
    </header>
    <main>
        {% block content %}{% endblock content %}
    </main>
    {% block scripts %}{% endblock scripts %}
</body>
</html>